import csv
import datetime as dt
import io
import secrets
import threading
import zipfile
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import FileResponse, JSONResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from PIL import Image, ImageOps

from . import fmv, tls, updater, vision
from .db import DB_PATH, UPLOAD_DIR, init_db, tx

app = FastAPI(title="Donation Tracker")
init_db()


# Tell browsers not to cache JSON API responses — without this, GET /api/items/{id}
# polling can return stale "analyzing" status long after the AI is done.
@app.middleware("http")
async def no_cache_api(request, call_next):
    response = await call_next(request)
    if request.url.path.startswith("/api/"):
        response.headers["Cache-Control"] = "no-store, must-revalidate"
        response.headers["Pragma"] = "no-cache"
    return response

# Apply any persisted LLM endpoint override from the settings table at startup.
def _apply_persisted_settings() -> None:
    with tx() as conn:
        url = conn.execute("SELECT value FROM settings WHERE key='llm_base_url'").fetchone()
        model = conn.execute("SELECT value FROM settings WHERE key='llm_model'").fetchone()
        fmv_rows = conn.execute(
            "SELECT category_key, low, median, high FROM fmv_overrides"
        ).fetchall()
    if url and url["value"]:
        vision.set_base_url(url["value"])
    if model and model["value"]:
        vision.set_model_override(model["value"])
    fmv.load_overrides([dict(r) for r in fmv_rows])

    # Auto-detect a hand-placed cert in data/certs/. If a cert exists and was
    # NOT generated by our self-signer, mark it as user-supplied so the
    # status panel labels it correctly.
    detected = tls.is_self_signed_by_us()
    if detected is False:
        with tx() as conn:
            conn.execute(
                "INSERT INTO settings(key,value) VALUES('ssl_custom','1') "
                "ON CONFLICT(key) DO UPDATE SET value='1'"
            )
    elif detected is True:
        # If we previously thought a custom cert was installed but the file
        # is now self-signed, clear the flag.
        with tx() as conn:
            conn.execute("DELETE FROM settings WHERE key='ssl_custom'")
_apply_persisted_settings()


# Auto-updater background loop. Reads settings on each tick so the UI toggle
# takes effect without a restart. Disabled by default.
def _updater_enabled() -> bool:
    return _get_setting("auto_update_enabled") == "1"


def _updater_interval_hours() -> float:
    raw = _get_setting("auto_update_interval_hours")
    try:
        return float(raw) if raw else updater.DEFAULT_INTERVAL_HOURS
    except ValueError:
        return updater.DEFAULT_INTERVAL_HOURS


updater.start_background_loop(_updater_enabled, _updater_interval_hours)


STATIC_DIR = Path(__file__).parent / "static"
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
app.mount("/uploads", StaticFiles(directory=UPLOAD_DIR), name="uploads")


# ---------- helpers ----------

def _row_to_item(row) -> dict:
    keys = row.keys() if hasattr(row, "keys") else []
    return {
        "id": row["id"],
        "created_at": row["created_at"],
        "image_url": f"/uploads/{row['image_filename']}",
        "description": row["description"],
        "category_key": row["category_key"],
        "category_label": row["category_label"],
        "condition": row["condition"],
        "fmv_low": row["fmv_low"],
        "fmv_median": row["fmv_median"],
        "fmv_high": row["fmv_high"],
        "estimated_value": row["estimated_value"],
        "value_overridden": bool(row["value_overridden"]) if "value_overridden" in keys else False,
        "quantity": row["quantity"],
        "notes": row["notes"],
        "status": row["status"],
        "error": row["error"],
        "event_id": row["event_id"],
        "donor_id": row["donor_id"],
        "donor_name": row["donor_name"] if "donor_name" in keys else None,
    }


def _row_to_cash(row) -> dict:
    keys = row.keys() if hasattr(row, "keys") else []
    return {
        "id": row["id"],
        "created_at": row["created_at"],
        "donation_date": row["donation_date"],
        "charity_name": row["charity_name"],
        "charity_address": row["charity_address"],
        "amount": row["amount"],
        "payment_method": row["payment_method"],
        "donor_id": row["donor_id"],
        "donor_name": row["donor_name"] if "donor_name" in keys else None,
        "receipt_filename": row["receipt_filename"],
        "receipt_url": f"/uploads/{row['receipt_filename']}" if row["receipt_filename"] else None,
        "notes": row["notes"],
    }


def _get_setting(key: str) -> str | None:
    with tx() as conn:
        row = conn.execute("SELECT value FROM settings WHERE key=?", (key,)).fetchone()
    return row["value"] if row else None


def _set_setting(key: str, value: str | None) -> None:
    with tx() as conn:
        if value is None:
            conn.execute("DELETE FROM settings WHERE key=?", (key,))
        else:
            conn.execute(
                "INSERT INTO settings(key,value) VALUES(?,?) "
                "ON CONFLICT(key) DO UPDATE SET value=excluded.value",
                (key, value),
            )


def _analyze_in_background(item_id: int, filename: str) -> None:
    image_path = UPLOAD_DIR / filename
    try:
        result = vision.analyze_image(image_path)
        est = fmv.estimate(result["category_key"], result["condition"])
        with tx() as conn:
            # Atomic: only write if the row is still 'analyzing'. If the user
            # already saved an edit (status='ready') or deleted the row, do nothing.
            conn.execute(
                """UPDATE items SET description=?, category_key=?, category_label=?,
                   condition=?, fmv_low=?, fmv_median=?, fmv_high=?,
                   estimated_value=?, quantity=?, status='ready', error=NULL
                   WHERE id=? AND status='analyzing'""",
                (result["description"], est["category_key"], est["category_label"],
                 result["condition"], est["fmv_low"], est["fmv_median"], est["fmv_high"],
                 est["estimated_value"], max(1, int(result["quantity"])), item_id),
            )
    except Exception as e:
        with tx() as conn:
            conn.execute(
                "UPDATE items SET status='failed', error=? WHERE id=? AND status='analyzing'",
                (str(e)[:500], item_id),
            )


def _row_to_event(row) -> dict:
    return {
        "id": row["id"],
        "created_at": row["created_at"],
        "donation_date": row["donation_date"],
        "charity_name": row["charity_name"],
        "charity_address": row["charity_address"],
        "notes": row["notes"],
    }


_IMAGE_SUFFIXES = (".jpg", ".jpeg", ".png", ".webp", ".heic", ".gif")
_RECEIPT_SUFFIXES = _IMAGE_SUFFIXES + (".pdf",)


def _save_upload(file: UploadFile) -> str:
    """Save an item photo, re-encoded as JPEG for size."""
    suffix = Path(file.filename or "upload.jpg").suffix.lower() or ".jpg"
    if suffix not in _IMAGE_SUFFIXES:
        suffix = ".jpg"
    name = f"{dt.datetime.now().strftime('%Y%m%d-%H%M%S')}-{secrets.token_hex(4)}{suffix}"
    raw_path = UPLOAD_DIR / name
    raw_path.write_bytes(file.file.read())

    # Re-encode to a sane size (max 1600px on long edge), preserve EXIF orientation.
    try:
        with Image.open(raw_path) as im:
            im = ImageOps.exif_transpose(im)
            im.thumbnail((1600, 1600))
            out_name = name if suffix in (".jpg", ".jpeg") else name.rsplit(".", 1)[0] + ".jpg"
            out_path = UPLOAD_DIR / out_name
            im.convert("RGB").save(out_path, "JPEG", quality=85, optimize=True)
            if out_path != raw_path:
                raw_path.unlink(missing_ok=True)
            return out_name
    except Exception:
        # If re-encode fails, keep the original bytes.
        return name


def _save_receipt(file: UploadFile) -> str:
    """Save a cash receipt: image (re-encoded for size) or PDF/other (saved as-is)."""
    suffix = Path(file.filename or "receipt").suffix.lower()
    if suffix in _IMAGE_SUFFIXES:
        return _save_upload(file)
    # Non-image: keep original bytes and extension. Whitelist a few common types.
    if suffix not in (".pdf", ".heic", ".txt"):
        # Default to .pdf for unknown content-types claiming pdf, else .bin
        ct = (file.content_type or "").lower()
        if "pdf" in ct: suffix = ".pdf"
        else: suffix = suffix or ".bin"
    name = f"{dt.datetime.now().strftime('%Y%m%d-%H%M%S')}-{secrets.token_hex(4)}{suffix}"
    (UPLOAD_DIR / name).write_bytes(file.file.read())
    return name


# ---------- routes ----------

@app.get("/")
def index():
    return FileResponse(STATIC_DIR / "index.html")


@app.get("/api/health")
def health(timeout: float = 5.0):
    """Fast LLM probe — only hits /v1/models, never attempts to load a model.
    Capped at 8 seconds even if the caller asks for more, so the UI never hangs."""
    timeout = min(max(timeout, 1.0), 8.0)
    result = vision.health_check(timeout_s=timeout)
    payload = {
        "ok": result["ok"],
        "model": result.get("model"),
        "error": result.get("error"),
        "available_count": result.get("available_count"),
        "llm_base_url": vision.LLM_BASE_URL,
        "llm_default_url": vision.DEFAULT_LLM_BASE_URL,
    }
    return JSONResponse(status_code=200 if result["ok"] else 503, content=payload)


@app.get("/api/settings/llm_base_url")
def get_llm_base_url():
    return {
        "current": vision.LLM_BASE_URL,
        "default": vision.DEFAULT_LLM_BASE_URL,
        "persisted": _get_setting("llm_base_url"),
    }


@app.post("/api/settings/llm_base_url")
async def set_llm_base_url(url: str = Form("")):
    """Update the active LLM endpoint and persist to the settings table.
    Empty string resets to the env default."""
    new_url = vision.set_base_url(url)
    _set_setting("llm_base_url", url.strip() or None)
    return {"current": new_url, "persisted": _get_setting("llm_base_url")}


@app.get("/api/settings/update")
def get_update_status():
    return {
        "enabled": _get_setting("auto_update_enabled") == "1",
        "interval_hours": _updater_interval_hours(),
        "default_interval_hours": updater.DEFAULT_INTERVAL_HOURS,
        "local": updater.local_commit_info(),
        "has_local_changes": updater.has_local_changes(),
    }


@app.get("/api/settings/update/remote")
def get_update_remote():
    """Hits the remote — slower (3-15s). Separate endpoint so the UI page
    load isn't blocked on a network call."""
    return {"remote": updater.remote_commit_info()}


@app.post("/api/settings/update")
async def set_update(enabled: str = Form(""), interval_hours: str = Form("")):
    if enabled:
        val = enabled.strip().lower() in ("true", "1", "yes", "on")
        _set_setting("auto_update_enabled", "1" if val else None)
    if interval_hours:
        try:
            n = max(0.25, float(interval_hours))
            _set_setting("auto_update_interval_hours", str(n))
        except ValueError:
            raise HTTPException(400, "interval_hours must be a number")
    return get_update_status()


@app.post("/api/settings/update/now")
def update_now():
    """Trigger a one-off git pull now. If anything changed the process will
    exit so systemd brings it back with the new code; the response is sent
    *before* exit so the UI sees success."""
    changed, msg, after = updater.pull_now()
    response = {"ok": True, "changed": changed, "message": msg, "local": after}
    if changed:
        # Schedule exit AFTER the response is flushed to the client.
        def _bye():
            import time, os as _os
            time.sleep(1)
            _os.kill(_os.getpid(), 15)  # SIGTERM, systemd restarts
        import threading; threading.Thread(target=_bye, daemon=True).start()
    return response


@app.get("/api/settings/ssl")
def get_ssl_status(request: Request):
    """Snapshot of TLS state. The 'current_scheme' is how *this request* arrived
    — it's the most reliable signal that HTTPS is actually serving."""
    cert_path = tls.CERT_PATH
    key_path = tls.KEY_PATH
    info = {
        "current_scheme": request.url.scheme,
        "https_active": request.url.scheme == "https",
        "https_enabled_setting": _get_setting("https_enabled") == "1",
        "ssl_custom": _get_setting("ssl_custom") == "1",
        "cert_path": str(cert_path),
        "key_path": str(key_path),
        "cert_exists": cert_path.exists(),
        "cert_subject": None,
        "cert_not_after": None,
        "cert_sans": [],
    }
    if cert_path.exists():
        try:
            from cryptography import x509
            cert = x509.load_pem_x509_certificate(cert_path.read_bytes())
            info["cert_subject"] = cert.subject.rfc4514_string()
            info["cert_not_after"] = cert.not_valid_after_utc.isoformat()
            try:
                san = cert.extensions.get_extension_for_class(x509.SubjectAlternativeName).value
                info["cert_sans"] = [str(g.value) for g in san]
            except Exception:
                pass
        except Exception as e:
            info["cert_error"] = str(e)
    return info


@app.post("/api/settings/ssl")
async def set_ssl_enabled(enabled: str = Form(...)):
    """Persist the HTTPS preference. Takes effect on next server restart."""
    val = enabled.strip().lower() in ("true", "1", "yes", "on")
    _set_setting("https_enabled", "1" if val else None)
    return {"https_enabled_setting": val,
            "note": "Restart the server (systemctl restart donationtracker) for this to take effect."}


@app.post("/api/settings/ssl/regenerate")
def regenerate_ssl_cert():
    """Delete the existing cert (custom or self-signed) and create a fresh
    self-signed one covering every current LAN IP."""
    try:
        if tls.CERT_PATH.exists(): tls.CERT_PATH.unlink()
        if tls.KEY_PATH.exists(): tls.KEY_PATH.unlink()
    except Exception as e:
        raise HTTPException(500, f"could not remove old cert: {e}")
    _set_setting("ssl_custom", None)
    tls.ensure_cert()
    return {"ok": True, "cert_path": str(tls.CERT_PATH),
            "note": "Self-signed cert regenerated. Restart the server to begin serving it."}


@app.post("/api/settings/ssl/upload")
async def upload_ssl_cert(
    cert: UploadFile = File(...),
    key: UploadFile = File(...),
):
    """Accept a user-supplied PEM cert + private key (e.g. from Let's Encrypt
    or mkcert) and install them as the active TLS material. Validated by
    parsing the cert AND verifying the key's public side matches it."""
    cert_bytes = await cert.read()
    key_bytes = await key.read()

    if b"BEGIN CERTIFICATE" not in cert_bytes:
        raise HTTPException(400, "cert file doesn't look like PEM (missing BEGIN CERTIFICATE)")
    if b"PRIVATE KEY" not in key_bytes:
        raise HTTPException(400, "key file doesn't look like PEM (missing PRIVATE KEY)")

    # Parse to make sure they're valid AND that the key matches the cert.
    try:
        from cryptography import x509
        from cryptography.hazmat.primitives import serialization
        cert_obj = x509.load_pem_x509_certificate(cert_bytes)
        key_obj = serialization.load_pem_private_key(key_bytes, password=None)
        cert_pub = cert_obj.public_key().public_bytes(
            encoding=serialization.Encoding.DER,
            format=serialization.PublicFormat.SubjectPublicKeyInfo)
        key_pub = key_obj.public_key().public_bytes(
            encoding=serialization.Encoding.DER,
            format=serialization.PublicFormat.SubjectPublicKeyInfo)
        if cert_pub != key_pub:
            raise HTTPException(400, "private key does not match the certificate")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(400, f"failed to parse cert/key: {e}")

    # Back up any existing material before overwriting.
    tls.CERT_PATH.parent.mkdir(parents=True, exist_ok=True)
    for p in (tls.CERT_PATH, tls.KEY_PATH):
        if p.exists():
            try: p.with_suffix(p.suffix + ".bak").write_bytes(p.read_bytes())
            except Exception: pass
    tls.CERT_PATH.write_bytes(cert_bytes)
    tls.KEY_PATH.write_bytes(key_bytes)
    try: import os; os.chmod(tls.KEY_PATH, 0o600)
    except Exception: pass

    _set_setting("ssl_custom", "1")
    return {"ok": True, "cert_path": str(tls.CERT_PATH),
            "note": "Custom cert installed. Restart the server (systemctl restart donationtracker) to begin serving it."}


@app.get("/api/settings/app_title")
def get_app_title():
    return {"current": _get_setting("app_title") or "Donations",
            "default": "Donations",
            "persisted": _get_setting("app_title")}


@app.post("/api/settings/app_title")
async def set_app_title(title: str = Form("")):
    title = title.strip()
    if len(title) > 100:
        raise HTTPException(400, "title too long (max 100 chars)")
    _set_setting("app_title", title or None)
    return {"current": title or "Donations", "persisted": title or None}


@app.get("/api/settings/llm_model")
def get_llm_model():
    return {
        "override": vision.LLM_MODEL_OVERRIDE,
        "persisted": _get_setting("llm_model"),
        "available": vision.list_available_models(timeout_s=5.0),
    }


@app.post("/api/settings/llm_model")
async def set_llm_model(model: str = Form("")):
    """Pin the LLM model. Empty string clears the override (auto-detect)."""
    new_model = vision.set_model_override(model)
    _set_setting("llm_model", model.strip() or None)
    return {"override": new_model, "persisted": _get_setting("llm_model")}


@app.get("/api/categories")
def categories():
    return fmv.category_options()


@app.get("/api/sources")
def sources():
    return {"sources": fmv.SOURCES, "methodology": fmv.METHODOLOGY,
            "categories": fmv.category_options(),
            "overrides_count": fmv.overrides_count()}


@app.post("/api/fmv/{category_key}")
async def upsert_fmv_override(
    category_key: str,
    low: float = Form(...),
    median: float = Form(...),
    high: float = Form(...),
):
    if category_key not in fmv.CATEGORIES:
        raise HTTPException(404, f"unknown category: {category_key}")
    if low < 0 or median < 0 or high < 0:
        raise HTTPException(400, "values must be non-negative")
    if not (low <= median <= high):
        raise HTTPException(400, "expected low ≤ median ≤ high")
    fmv.set_override(category_key, low, median, high)
    with tx() as conn:
        conn.execute(
            "INSERT INTO fmv_overrides(category_key, low, median, high) "
            "VALUES(?,?,?,?) "
            "ON CONFLICT(category_key) DO UPDATE SET "
            "low=excluded.low, median=excluded.median, high=excluded.high, "
            "updated_at=datetime('now')",
            (category_key, low, median, high),
        )
    return {"ok": True, "category_key": category_key,
            "low": low, "median": median, "high": high, "is_overridden": True}


@app.delete("/api/fmv/{category_key}")
def reset_fmv_override(category_key: str):
    """Revert a single category to the bundled default."""
    if category_key not in fmv.CATEGORIES:
        raise HTTPException(404, f"unknown category: {category_key}")
    fmv.clear_override(category_key)
    with tx() as conn:
        conn.execute("DELETE FROM fmv_overrides WHERE category_key=?", (category_key,))
    base = fmv.CATEGORIES[category_key]
    return {"ok": True, "category_key": category_key,
            "low": base["low"], "median": base["median"], "high": base["high"],
            "is_overridden": False}


@app.delete("/api/fmv")
def reset_all_fmv_overrides():
    """Wipe every user override and revert to bundled defaults."""
    fmv.clear_all_overrides()
    with tx() as conn:
        cur = conn.execute("DELETE FROM fmv_overrides")
        removed = cur.rowcount
    return {"ok": True, "removed": removed}


# ---- factory reset ----

FACTORY_RESET_PHRASE = "DELETE EVERYTHING"


@app.post("/api/factory_reset")
async def factory_reset(confirm: str = Form(...)):
    """Wipe all donor data: items, events, donors, cash, settings, FMV overrides,
    and every uploaded file. Backups under data/backups/ are preserved.
    Requires the exact confirmation phrase."""
    if confirm.strip() != FACTORY_RESET_PHRASE:
        raise HTTPException(400, f'must send confirm="{FACTORY_RESET_PHRASE}"')
    with tx() as conn:
        for table in ("items", "events", "donors", "cash_donations",
                      "settings", "fmv_overrides"):
            conn.execute(f"DELETE FROM {table}")
        try:
            conn.execute("DELETE FROM sqlite_sequence")
        except Exception:
            pass
    # Wipe every uploaded photo / receipt
    removed_files = 0
    for p in UPLOAD_DIR.iterdir():
        if p.is_file():
            try: p.unlink(); removed_files += 1
            except Exception: pass
    # Reset in-memory state
    fmv.clear_all_overrides()
    vision.set_base_url(None)         # back to env default
    vision.set_model_override(None)
    return {"ok": True, "removed_files": removed_files}


@app.get("/sources", response_class=FileResponse)
def sources_page():
    return FileResponse(STATIC_DIR / "sources.html")


# --- items ---

@app.post("/api/items")
async def create_item(image: UploadFile = File(...), donor_id: int | None = Form(None)):
    """Upload an image, save immediately with status='analyzing', kick off vision in background."""
    if not image.content_type or not image.content_type.startswith("image/"):
        raise HTTPException(400, "image/* required")

    filename = _save_upload(image)
    # Validate the donor still exists; if not, fall back to NULL rather than 500.
    # The "default donor" is a per-device choice and is stored client-side
    # (localStorage), then sent on each upload — there's no server-side default.
    if donor_id is not None:
        with tx() as conn:
            if not conn.execute("SELECT 1 FROM donors WHERE id=?", (donor_id,)).fetchone():
                donor_id = None

    with tx() as conn:
        cur = conn.execute(
            """INSERT INTO items
               (image_filename, description, category_key, category_label,
                condition, fmv_low, fmv_median, fmv_high, estimated_value, quantity, status, donor_id)
               VALUES (?,?,?,?,?,?,?,?,?,?, 'analyzing', ?)""",
            (filename, "", None, None, None, None, None, None, None, 1, donor_id),
        )
        item_id = cur.lastrowid
        row = _fetch_item_row(conn, item_id)

    threading.Thread(
        target=_analyze_in_background, args=(item_id, filename), daemon=True
    ).start()
    return _row_to_item(row)


def _fetch_item_row(conn, item_id: int):
    return conn.execute(
        "SELECT i.*, d.name AS donor_name FROM items i "
        "LEFT JOIN donors d ON i.donor_id = d.id WHERE i.id=?",
        (item_id,),
    ).fetchone()


@app.post("/api/items/{item_id}/reanalyze")
def reanalyze(item_id: int):
    with tx() as conn:
        row = conn.execute("SELECT * FROM items WHERE id=?", (item_id,)).fetchone()
        if not row:
            raise HTTPException(404, "not found")
        conn.execute("UPDATE items SET status='analyzing', error=NULL WHERE id=?", (item_id,))
        filename = row["image_filename"]
    threading.Thread(
        target=_analyze_in_background, args=(item_id, filename), daemon=True
    ).start()
    return {"ok": True}


@app.get("/api/items")
def list_items(event_id: int | None = None, unassigned: bool = False,
               donor_id: int | None = None, since_id: int | None = None):
    sql = ("SELECT i.*, d.name AS donor_name FROM items i "
           "LEFT JOIN donors d ON i.donor_id = d.id")
    params: list = []
    where = []
    if unassigned:
        where.append("i.event_id IS NULL")
    elif event_id is not None:
        where.append("i.event_id = ?"); params.append(event_id)
    if donor_id is not None:
        where.append("i.donor_id = ?"); params.append(donor_id)
    if since_id is not None:
        where.append("i.id > ?"); params.append(since_id)
    if where:
        sql += " WHERE " + " AND ".join(where)
    sql += " ORDER BY i.id DESC"
    with tx() as conn:
        rows = conn.execute(sql, params).fetchall()
    return [_row_to_item(r) for r in rows]


@app.get("/api/items/{item_id}")
def get_item(item_id: int):
    with tx() as conn:
        row = _fetch_item_row(conn, item_id)
    if not row:
        raise HTTPException(404, "not found")
    return _row_to_item(row)


@app.patch("/api/items/{item_id}")
async def update_item(
    item_id: int,
    description: str | None = Form(None),
    category_key: str | None = Form(None),
    condition: str | None = Form(None),
    quantity: int | None = Form(None),
    estimated_value: float | None = Form(None),
    value_overridden: str | None = Form(None),  # "true"/"false"/"1"/"0"/None=unchanged
    notes: str | None = Form(None),
    donor_id: str | None = Form(None),
):
    with tx() as conn:
        row = conn.execute("SELECT * FROM items WHERE id=?", (item_id,)).fetchone()
        if not row:
            raise HTTPException(404, "not found")
        if donor_id is None:
            new_donor = row["donor_id"]
        elif donor_id == "":
            new_donor = None
        else:
            new_donor = int(donor_id)

        new_desc = description if description is not None else row["description"]
        new_cond = condition if condition is not None else row["condition"]
        new_qty = quantity if quantity is not None else row["quantity"]
        new_notes = notes if notes is not None else row["notes"]

        # Decide override flag: explicit form field wins, else preserve, but
        # always treat the row as overridden if the user typed a value that
        # differs from what auto would compute below.
        if value_overridden is None:
            new_override = bool(row["value_overridden"])
        else:
            new_override = value_overridden.lower() in ("true", "1", "yes", "on")

        # Resolve category/FMV range
        if category_key is not None and category_key != row["category_key"]:
            est = fmv.estimate(category_key, new_cond)
            new_cat_key = est["category_key"]
            new_cat_label = est["category_label"]
            new_low, new_med, new_high = est["fmv_low"], est["fmv_median"], est["fmv_high"]
            auto_value = est["estimated_value"]
        else:
            new_cat_key = row["category_key"]
            new_cat_label = row["category_label"]
            new_low, new_med, new_high = row["fmv_low"], row["fmv_median"], row["fmv_high"]
            if new_cat_key:
                est = fmv.estimate(new_cat_key, new_cond)
                auto_value = est["estimated_value"]
            else:
                auto_value = row["estimated_value"]

        # Resolve final value:
        #   - override mode: trust what the user sent (or keep current)
        #   - auto mode: ignore any sent value, use auto_value
        if new_override:
            new_value = estimated_value if estimated_value is not None else row["estimated_value"]
        else:
            new_value = auto_value

        conn.execute(
            """UPDATE items SET description=?, category_key=?, category_label=?,
               condition=?, fmv_low=?, fmv_median=?, fmv_high=?,
               estimated_value=?, value_overridden=?, quantity=?, notes=?, donor_id=?,
               status='ready', error=NULL
               WHERE id=?""",
            (new_desc, new_cat_key, new_cat_label, new_cond,
             new_low, new_med, new_high, new_value, 1 if new_override else 0,
             new_qty, new_notes, new_donor, item_id),
        )
        row = _fetch_item_row(conn, item_id)
    return _row_to_item(row)


@app.delete("/api/items/{item_id}")
def delete_item(item_id: int):
    with tx() as conn:
        row = conn.execute("SELECT image_filename FROM items WHERE id=?", (item_id,)).fetchone()
        if not row:
            raise HTTPException(404, "not found")
        conn.execute("DELETE FROM items WHERE id=?", (item_id,))
    try:
        (UPLOAD_DIR / row["image_filename"]).unlink(missing_ok=True)
    except Exception:
        pass
    return {"ok": True}


# --- events ---

@app.post("/api/events")
async def create_event(
    charity_name: str = Form(...),
    donation_date: str = Form(...),
    charity_address: str | None = Form(None),
    notes: str | None = Form(None),
):
    with tx() as conn:
        cur = conn.execute(
            """INSERT INTO events (donation_date, charity_name, charity_address, notes)
               VALUES (?,?,?,?)""",
            (donation_date, charity_name, charity_address, notes),
        )
        ev_id = cur.lastrowid
        row = conn.execute("SELECT * FROM events WHERE id=?", (ev_id,)).fetchone()
    return _row_to_event(row)


@app.get("/api/events")
def list_events():
    with tx() as conn:
        rows = conn.execute(
            "SELECT * FROM events ORDER BY donation_date DESC, id DESC"
        ).fetchall()
        events = [_row_to_event(r) for r in rows]
        # attach per-event totals
        for ev in events:
            agg = conn.execute(
                "SELECT COUNT(*) AS n, COALESCE(SUM(estimated_value*quantity),0) AS total "
                "FROM items WHERE event_id=?",
                (ev["id"],),
            ).fetchone()
            ev["item_count"] = agg["n"]
            ev["total_value"] = agg["total"]
    return events


@app.get("/api/events/{event_id}")
def get_event(event_id: int):
    with tx() as conn:
        row = conn.execute("SELECT * FROM events WHERE id=?", (event_id,)).fetchone()
        if not row:
            raise HTTPException(404, "not found")
        ev = _row_to_event(row)
        items = [_row_to_item(r) for r in conn.execute(
            "SELECT i.*, d.name AS donor_name FROM items i "
            "LEFT JOIN donors d ON i.donor_id = d.id "
            "WHERE i.event_id=? ORDER BY i.id ASC", (event_id,)
        ).fetchall()]
    ev["items"] = items
    ev["item_count"] = len(items)
    ev["total_value"] = sum((i["estimated_value"] or 0) * (i["quantity"] or 1) for i in items)
    return ev


@app.post("/api/events/{event_id}/assign")
async def assign_items(event_id: int, item_ids: str = Form("")):
    """Assign specific items (comma-separated ids) to this event."""
    with tx() as conn:
        ev = conn.execute("SELECT id FROM events WHERE id=?", (event_id,)).fetchone()
        if not ev:
            raise HTTPException(404, "event not found")
        ids = [int(x) for x in item_ids.split(",") if x.strip()]
        if ids:
            placeholders = ",".join("?" * len(ids))
            conn.execute(
                f"UPDATE items SET event_id=? WHERE id IN ({placeholders})",
                [event_id, *ids],
            )
    return get_event(event_id)


@app.post("/api/events/{event_id}/assign_all_unassigned")
def assign_all_unassigned(event_id: int):
    """Assign every currently-unassigned item to this event."""
    with tx() as conn:
        ev = conn.execute("SELECT id FROM events WHERE id=?", (event_id,)).fetchone()
        if not ev:
            raise HTTPException(404, "event not found")
        cur = conn.execute(
            "UPDATE items SET event_id=? WHERE event_id IS NULL", (event_id,)
        )
        moved = cur.rowcount
    payload = get_event(event_id)
    payload["moved"] = moved
    return payload


@app.post("/api/events/{event_id}/unassign")
async def unassign_items(event_id: int, item_ids: str = Form(...)):
    ids = [int(x) for x in item_ids.split(",") if x.strip()]
    if not ids:
        return get_event(event_id)
    with tx() as conn:
        placeholders = ",".join("?" * len(ids))
        conn.execute(
            f"UPDATE items SET event_id=NULL WHERE event_id=? AND id IN ({placeholders})",
            [event_id, *ids],
        )
    return get_event(event_id)


@app.delete("/api/events/{event_id}")
def delete_event(event_id: int):
    with tx() as conn:
        row = conn.execute("SELECT id FROM events WHERE id=?", (event_id,)).fetchone()
        if not row:
            raise HTTPException(404, "not found")
        conn.execute("UPDATE items SET event_id=NULL WHERE event_id=?", (event_id,))
        conn.execute("DELETE FROM events WHERE id=?", (event_id,))
    return {"ok": True}


@app.get("/receipt/{event_id}", response_class=FileResponse)
def receipt(event_id: int):
    # Receipt is rendered client-side; serve the same shell.
    return FileResponse(STATIC_DIR / "receipt.html")


# --- year-end tax summary ---

@app.get("/api/summary/{year}")
def summary(year: int):
    """Tax-year summary grouped by charity. Year is matched against events.donation_date (YYYY-...)."""
    y = f"{year:04d}-"
    with tx() as conn:
        events = conn.execute(
            "SELECT * FROM events WHERE donation_date LIKE ? ORDER BY donation_date ASC, id ASC",
            (y + "%",),
        ).fetchall()
        by_charity: dict[str, dict] = {}
        grand_total = 0.0
        grand_items = 0
        cat_totals: dict[str, dict] = {}
        for ev in events:
            ev_d = _row_to_event(ev)
            items = [_row_to_item(r) for r in conn.execute(
                "SELECT i.*, d.name AS donor_name FROM items i "
                "LEFT JOIN donors d ON i.donor_id = d.id "
                "WHERE i.event_id=? ORDER BY i.id ASC", (ev["id"],)
            ).fetchall()]
            ev_d["items"] = items
            ev_d["item_count"] = len(items)
            ev_d["total_value"] = sum((i["estimated_value"] or 0) * (i["quantity"] or 1) for i in items)
            grand_total += ev_d["total_value"]
            grand_items += ev_d["item_count"]
            key = ev["charity_name"].strip()
            grp = by_charity.setdefault(key, {
                "charity_name": key,
                "charity_address": ev["charity_address"],
                "events": [],
                "total_value": 0.0,
                "item_count": 0,
            })
            grp["events"].append(ev_d)
            grp["total_value"] += ev_d["total_value"]
            grp["item_count"] += ev_d["item_count"]
            if not grp["charity_address"] and ev["charity_address"]:
                grp["charity_address"] = ev["charity_address"]
            for i in items:
                k = i["category_label"] or "Other"
                ct = cat_totals.setdefault(k, {"category": k, "qty": 0, "value": 0.0})
                ct["qty"] += i["quantity"] or 1
                ct["value"] += (i["estimated_value"] or 0) * (i["quantity"] or 1)

        unassigned_in_year = conn.execute(
            "SELECT COUNT(*) AS n FROM items WHERE event_id IS NULL "
            "AND substr(created_at,1,4)=?",
            (str(year),),
        ).fetchone()["n"]

    # Per-donor breakdown for the year
    donor_totals: dict[str, dict] = {}
    for grp in by_charity.values():
        for ev in grp["events"]:
            for i in ev["items"]:
                key = i.get("donor_name") or "(unspecified donor)"
                dt_ = donor_totals.setdefault(key, {
                    "donor_name": key,
                    "donor_id": i.get("donor_id"),
                    "item_count": 0,
                    "total_value": 0.0,
                    "by_category": {},
                })
                qty = i["quantity"] or 1
                val = (i["estimated_value"] or 0) * qty
                dt_["item_count"] += qty
                dt_["total_value"] += val
                ck = i["category_label"] or "Other"
                cb = dt_["by_category"].setdefault(ck, {"category": ck, "qty": 0, "value": 0.0})
                cb["qty"] += qty
                cb["value"] += val
    for d in donor_totals.values():
        d["by_category"] = sorted(d["by_category"].values(), key=lambda x: -x["value"])

    # Cash donations for this year
    cash_rows = list_cash(year=year)
    cash_total = sum(c["amount"] or 0 for c in cash_rows)
    cash_by_charity: dict[str, dict] = {}
    for c in cash_rows:
        k = c["charity_name"].strip()
        g = cash_by_charity.setdefault(k, {"charity_name": k, "items": [], "total": 0.0})
        g["items"].append(c)
        g["total"] += c["amount"] or 0

    return {
        "year": year,
        "charities": list(by_charity.values()),
        "category_totals": sorted(cat_totals.values(), key=lambda x: -x["value"]),
        "donor_totals": sorted(donor_totals.values(), key=lambda x: -x["total_value"]),
        "grand_total": grand_total,
        "grand_items": grand_items,
        "event_count": len(events),
        "unassigned_in_year": unassigned_in_year,
        "cash_total": cash_total,
        "cash_count": len(cash_rows),
        "cash_by_charity": list(cash_by_charity.values()),
        "combined_total": grand_total + cash_total,
        "form_8283_required": grand_total > 500,
        "appraisal_required_threshold_hit": any(
            ((i["estimated_value"] or 0) * (i["quantity"] or 1)) > 5000
            for grp in by_charity.values()
            for ev in grp["events"]
            for i in ev["items"]
        ),
    }


# --- cash donations ---

@app.post("/api/cash")
async def create_cash(
    charity_name: str = Form(...),
    donation_date: str = Form(...),
    amount: float = Form(...),
    payment_method: str = Form("cash"),
    charity_address: str | None = Form(None),
    donor_id: str | None = Form(None),
    notes: str | None = Form(None),
    receipt: UploadFile | None = File(None),
):
    if amount < 0:
        raise HTTPException(400, "amount must be non-negative")
    did: int | None = None
    if donor_id and donor_id.strip():
        try: did = int(donor_id)
        except ValueError: did = None
    fname: str | None = None
    if receipt is not None and receipt.filename:
        fname = _save_receipt(receipt)
    with tx() as conn:
        cur = conn.execute(
            """INSERT INTO cash_donations
               (donation_date, charity_name, charity_address, amount, payment_method,
                donor_id, receipt_filename, notes)
               VALUES (?,?,?,?,?,?,?,?)""",
            (donation_date, charity_name, charity_address, amount, payment_method,
             did, fname, notes),
        )
        row = _fetch_cash_row(conn, cur.lastrowid)
    return _row_to_cash(row)


def _fetch_cash_row(conn, cash_id: int):
    return conn.execute(
        "SELECT c.*, d.name AS donor_name FROM cash_donations c "
        "LEFT JOIN donors d ON c.donor_id = d.id WHERE c.id=?",
        (cash_id,),
    ).fetchone()


@app.get("/api/cash")
def list_cash(year: int | None = None):
    sql = ("SELECT c.*, d.name AS donor_name FROM cash_donations c "
           "LEFT JOIN donors d ON c.donor_id = d.id")
    params: list = []
    if year is not None:
        sql += " WHERE c.donation_date LIKE ?"
        params.append(f"{year:04d}-%")
    sql += " ORDER BY c.donation_date DESC, c.id DESC"
    with tx() as conn:
        rows = conn.execute(sql, params).fetchall()
    return [_row_to_cash(r) for r in rows]


@app.patch("/api/cash/{cash_id}")
async def update_cash(
    cash_id: int,
    charity_name: str | None = Form(None),
    donation_date: str | None = Form(None),
    amount: float | None = Form(None),
    payment_method: str | None = Form(None),
    charity_address: str | None = Form(None),
    donor_id: str | None = Form(None),
    notes: str | None = Form(None),
    receipt: UploadFile | None = File(None),
    remove_receipt: str | None = Form(None),  # "true" to delete the existing one
):
    with tx() as conn:
        row = conn.execute("SELECT * FROM cash_donations WHERE id=?", (cash_id,)).fetchone()
        if not row:
            raise HTTPException(404, "not found")
        if donor_id is None:
            new_donor = row["donor_id"]
        elif donor_id == "":
            new_donor = None
        else:
            new_donor = int(donor_id)

        new_receipt = row["receipt_filename"]
        old_to_remove: str | None = None
        if receipt is not None and receipt.filename:
            new_receipt = _save_receipt(receipt)
            if row["receipt_filename"] and row["receipt_filename"] != new_receipt:
                old_to_remove = row["receipt_filename"]
        elif remove_receipt and remove_receipt.lower() in ("true", "1", "yes", "on"):
            if row["receipt_filename"]:
                old_to_remove = row["receipt_filename"]
            new_receipt = None

        conn.execute(
            """UPDATE cash_donations SET
               charity_name=?, donation_date=?, charity_address=?,
               amount=?, payment_method=?, donor_id=?, notes=?, receipt_filename=?
               WHERE id=?""",
            (charity_name if charity_name is not None else row["charity_name"],
             donation_date if donation_date is not None else row["donation_date"],
             charity_address if charity_address is not None else row["charity_address"],
             amount if amount is not None else row["amount"],
             payment_method if payment_method is not None else row["payment_method"],
             new_donor,
             notes if notes is not None else row["notes"],
             new_receipt,
             cash_id),
        )
        row = _fetch_cash_row(conn, cash_id)
    if old_to_remove:
        try: (UPLOAD_DIR / old_to_remove).unlink(missing_ok=True)
        except Exception: pass
    return _row_to_cash(row)


@app.delete("/api/cash/{cash_id}")
def delete_cash(cash_id: int):
    with tx() as conn:
        row = conn.execute("SELECT receipt_filename FROM cash_donations WHERE id=?",
                           (cash_id,)).fetchone()
        if not row:
            raise HTTPException(404, "not found")
        conn.execute("DELETE FROM cash_donations WHERE id=?", (cash_id,))
    if row["receipt_filename"]:
        try: (UPLOAD_DIR / row["receipt_filename"]).unlink(missing_ok=True)
        except Exception: pass
    return {"ok": True}


# --- donors ---

@app.get("/api/donors")
def list_donors():
    with tx() as conn:
        rows = conn.execute(
            """SELECT d.id, d.name, d.created_at,
               (SELECT COUNT(*) FROM items WHERE donor_id=d.id) AS item_count,
               (SELECT COALESCE(SUM(estimated_value*quantity),0)
                  FROM items WHERE donor_id=d.id) AS items_value,
               (SELECT COUNT(*) FROM cash_donations WHERE donor_id=d.id) AS cash_count,
               (SELECT COALESCE(SUM(amount),0)
                  FROM cash_donations WHERE donor_id=d.id) AS cash_value
               FROM donors d
               ORDER BY d.name COLLATE NOCASE ASC"""
        ).fetchall()
    out = []
    for r in rows:
        d = dict(r)
        d["total_value"] = (d["items_value"] or 0) + (d["cash_value"] or 0)
        out.append(d)
    return out


@app.post("/api/donors")
async def create_donor(name: str = Form(...)):
    name = name.strip()
    if not name:
        raise HTTPException(400, "name is required")
    with tx() as conn:
        try:
            cur = conn.execute("INSERT INTO donors(name) VALUES(?)", (name,))
        except Exception as e:
            raise HTTPException(409, f"donor already exists: {e}")
        d = conn.execute("SELECT * FROM donors WHERE id=?", (cur.lastrowid,)).fetchone()
    return dict(d)


@app.patch("/api/donors/{donor_id}")
async def rename_donor(donor_id: int, name: str = Form(...)):
    name = name.strip()
    if not name:
        raise HTTPException(400, "name is required")
    with tx() as conn:
        cur = conn.execute("UPDATE donors SET name=? WHERE id=?", (name, donor_id))
        if cur.rowcount == 0:
            raise HTTPException(404, "not found")
        d = conn.execute("SELECT * FROM donors WHERE id=?", (donor_id,)).fetchone()
    return dict(d)


@app.delete("/api/donors/{donor_id}")
def delete_donor(donor_id: int):
    with tx() as conn:
        # Items keep their record (donor_id becomes NULL via FK ON DELETE SET NULL,
        # but our migration didn't enforce that for old rows; do it explicitly).
        conn.execute("UPDATE items SET donor_id=NULL WHERE donor_id=?", (donor_id,))
        cur = conn.execute("DELETE FROM donors WHERE id=?", (donor_id,))
        if cur.rowcount == 0:
            raise HTTPException(404, "not found")
    # Clear default if it pointed here
    if _get_setting("default_donor_id") == str(donor_id):
        _set_setting("default_donor_id", None)
    return {"ok": True}


# Note: there is no server-side "default donor". Each device chooses its own
# default and stores it in localStorage; that choice is sent with every upload.


@app.get("/api/years")
def years():
    """All years that have at least one donation event."""
    with tx() as conn:
        rows = conn.execute(
            "SELECT DISTINCT substr(donation_date,1,4) AS y FROM events ORDER BY y DESC"
        ).fetchall()
    return [int(r["y"]) for r in rows if r["y"] and r["y"].isdigit()]


@app.get("/api/export")
def export_zip():
    """Stream a ZIP containing the SQLite DB, an Excel-readable CSV, and every photo."""
    with tx() as conn:
        rows = conn.execute("""
            SELECT i.*, e.donation_date, e.charity_name, e.charity_address, e.notes AS event_notes,
                   d.name AS donor_name
            FROM items i
            LEFT JOIN events e ON i.event_id = e.id
            LEFT JOIN donors d ON i.donor_id = d.id
            ORDER BY e.donation_date IS NULL, e.donation_date ASC, i.id ASC
        """).fetchall()

    csv_buf = io.StringIO()
    csv_buf.write("﻿")  # UTF-8 BOM so Excel detects encoding
    writer = csv.writer(csv_buf)
    writer.writerow([
        "item_id", "photo_uploaded_at", "donor", "donation_date", "charity_name", "charity_address",
        "description", "category", "category_key", "condition",
        "fmv_low", "fmv_median", "fmv_high", "value_per_unit", "quantity", "subtotal",
        "item_notes", "drop_off_notes", "status", "image_file", "image_relpath",
    ])
    for r in rows:
        qty = r["quantity"] or 1
        val = r["estimated_value"] or 0
        writer.writerow([
            r["id"], r["created_at"], r["donor_name"] or "",
            r["donation_date"] or "", r["charity_name"] or "", r["charity_address"] or "",
            r["description"] or "", r["category_label"] or "", r["category_key"] or "", r["condition"] or "",
            r["fmv_low"] if r["fmv_low"] is not None else "",
            r["fmv_median"] if r["fmv_median"] is not None else "",
            r["fmv_high"] if r["fmv_high"] is not None else "",
            val, qty, round(val * qty, 2),
            r["notes"] or "", r["event_notes"] or "", r["status"] or "",
            r["image_filename"], f"images/{r['image_filename']}",
        ])
    csv_bytes = csv_buf.getvalue().encode("utf-8")

    # Cash donations CSV
    cash_csv = io.StringIO(); cash_csv.write("﻿")
    cw = csv.writer(cash_csv)
    cw.writerow(["cash_id", "donation_date", "donor", "charity_name", "charity_address",
                 "amount", "payment_method", "receipt_file", "receipt_relpath", "notes"])
    with tx() as conn:
        cash_rows = conn.execute(
            "SELECT c.*, d.name AS donor_name FROM cash_donations c "
            "LEFT JOIN donors d ON c.donor_id = d.id "
            "ORDER BY c.donation_date ASC, c.id ASC"
        ).fetchall()
    for r in cash_rows:
        rf = r["receipt_filename"]
        cw.writerow([
            r["id"], r["donation_date"], r["donor_name"] or "",
            r["charity_name"] or "", r["charity_address"] or "",
            r["amount"], r["payment_method"] or "",
            rf or "", f"images/{rf}" if rf else "",
            r["notes"] or "",
        ])
    cash_bytes = cash_csv.getvalue().encode("utf-8")

    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("donations.csv", csv_bytes)
        zf.writestr("cash_donations.csv", cash_bytes)
        if DB_PATH.exists():
            zf.write(DB_PATH, "donations.db")
        readme = (
            "Donation Tracker export\n"
            "=======================\n\n"
            "donations.csv       - one row per non-cash item, opens in Excel (UTF-8 with BOM).\n"
            "                      The 'image_relpath' column points to the file in this archive.\n"
            "cash_donations.csv  - one row per cash gift; 'receipt_relpath' points at the receipt image.\n"
            "donations.db        - SQLite database. Drop back into the app's data/ directory to restore.\n"
            "images/             - every photo, named by its original upload filename.\n"
            "\nFair-market values are based on Goodwill / Salvation Army valuation guides\n"
            "per IRS Pub. 561. Cash donations follow IRS Pub. 526 recordkeeping rules.\n"
        )
        zf.writestr("README.txt", readme)
        for img in UPLOAD_DIR.iterdir():
            if img.is_file():
                zf.write(img, f"images/{img.name}")
    zip_buf.seek(0)

    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    filename = f"donations-export-{stamp}.zip"
    return StreamingResponse(
        zip_buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@app.get("/summary", response_class=FileResponse)
def summary_page_default():
    return FileResponse(STATIC_DIR / "summary.html")


@app.get("/summary/{year}", response_class=FileResponse)
def summary_page(year: int):
    return FileResponse(STATIC_DIR / "summary.html")
